- name: GetHostname
  hosts: paskdev-1_420530f3-ca3b-cfaf-3282-825ec726cbb3
  tasks:
    - name: Hostname
      shell: |
        hostname
        whoami
      register: shell_output
    - name: Print data
      debug: 
        var: shell_output
