- name: GetHostname
  hosts: all
  tasks:
    - name: Hostname
      shell: |
        hostname
        whoami
      register: shell_output
    - name: Print data
      debug: 
        var: shell_output
